spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_HOST}/realms/master/protocol/openid-connect/certs
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_HOST}/realms/local-services-platform

server:
  port: 8072
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: gateway-server
    description: Gateway Server for Local Services Platform

logging:
  level:
    ROOT: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
  pattern:
    console: GATEWAY-SERVER >> %msg%n

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/

app:
  keycloak:
    api-key: ${KEYCLOAK_API_KEY}