spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: false

server:
  port: 8072

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    env:
      enabled: true

info:
  app:
    name: "gateway-server"
    description: "Gateway Server for Local Services Platform"

logging:
  level:
    ROOT: INFO
  pattern:
    console: "GATEWAY-SERVER >> %msg%n"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/