spring:
  datasource:
    url: jdbc:postgresql://${BOOKING_POSTGRES_URL}:5433/${BOOKING_POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${BOOKING_POSTGRES_USER}
    password: ${BOOKING_POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    ROOT: INFO
  pattern:
    console: BOOKING-SERVICE >> %msg%n