server:
  port: 9000
spring:
  profiles:
    default: dev

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/

info:
  app:
    name: "offer-service"
    description: "Offer Service for Local Services Platform"