spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    base-path: /actuator
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    ROOT: INFO
  pattern:
    console: EUREKA-SERVER >> %msg%n