name: local-services-platform
services:

  user-postgres:
    image: postgres:16-alpine
    container_name: user-postgres
    environment:
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/user-postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - backend

  booking-postgres:
    image: postgres:16-alpine
    container_name: booking-postgres
    environment:
      POSTGRES_USER: ${BOOKING_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BOOKING_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BOOKING_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ../volumes/booking-postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - backend

  offer-mongo:
    image: mongo:7
    container_name: offer-mongo
    ports:
      - "${OFFER_MONGO_INITDB_PORT:-7080}:27017"
    volumes:
      - ../volumes/offer-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${OFFER_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${OFFER_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${OFFER_MONGO_INITDB_DATABASE}
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_API_KEY: ${KEYCLOAK_API_KEY}
      GATEWAY_URL: ${GATEWAY_URL}
    ports:
      - "${KEYCLOAK_PORT_HOST:-7080}:8080"
    volumes:
      - ../volumes/keycloak_data:/opt/keycloak/data
      - ../volumes/keycloak_themes:/opt/keycloak/themes
      - ../volumes/keycloak_providers:/opt/keycloak/providers
    networks:
      - backend

  kafka:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "${KAFKA_EXTERNAL_PORT:-9092}:${KAFKA_EXTERNAL_PORT:-9092}"
    volumes:
      - ../volumes/kafka:/bitnami
      - ../volumes/kafka/logs:/var/lib/kafka/data
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_NODE_ID=${KAFKA_CFG_NODE_ID}
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:${KAFKA_EXTERNAL_PORT:-9092},CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:${KAFKA_EXTERNAL_PORT:-9092}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=168
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - backend

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "8081:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:29092
    depends_on:
      - kafka
    networks:
      - backend

networks:
  backend:
    driver: bridge