name: local-services-platform
services:

  user-postgres:
    image: postgres:16-alpine
    container_name: user-postgres
    environment:
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - backend

  booking-postgres:
    image: postgres:16-alpine
    container_name: booking-postgres
    environment:
      POSTGRES_USER: ${BOOKING_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BOOKING_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BOOKING_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - backend

  offer-mongo:
    image: mongo:7
    container_name: offer-mongo
    ports:
      - "27017:27017"
    volumes:
      - ../volumes/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${OFFER_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${OFFER_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${OFFER_MONGO_INITDB_DATABASE}
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - backend

  kafka:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "9092:9092"
    volumes:
      - ../volumes/kafka:/bitnami
      - ../volumes/kafka/logs:/var/lib/kafka/data
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_NODE_ID=${KAFKA_CFG_NODE_ID}
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=168
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - backend

networks:
  backend:
    driver: bridge